from __future__ import annotations

def get_bootstrap_dataset():
    positive = [
        "I absolutely loved this movie and every scene felt exciting",
        "The service was fantastic and I would happily come back",
        "This product works really well and exceeded my expectations",
        "The experience was smooth, enjoyable, and surprisingly helpful",
        "I had a great time and the staff were very friendly",
        "The update made the app faster and easier to use",
        "What a wonderful story, I felt happy by the end",
        "The design looks clean and professional",
        "This was a solid performance with excellent direction",
        "I am impressed by the quality and attention to detail",
        "Not bad at all, I actually liked it a lot",
        "Pretty good overall and worth recommending",
        "The food was delicious and arrived right on time",
        "I enjoyed the pacing, acting, and soundtrack",
        "Everything worked perfectly from start to finish",
        "The support team resolved my issue quickly",
        "The camera quality is excellent in daylight",
        "It feels premium and performs smoothly",
        "This is one of the better tools I have used",
        "The interface is intuitive and pleasant to navigate",
        "Great visuals and strong emotional payoff",
        "I really liked how easy the setup was",
        "The battery life is amazing for daily use",
        "A satisfying and memorable experience",
        "The lessons were clear, practical, and engaging",
        "I found the content useful and well organized",
        "The feature set is impressive and genuinely useful",
        "I would definitely watch this again",
        "The delivery was quick and the item was in perfect condition",
        "The team did an excellent job on this release",
    ]

    negative = [
        "I hated this movie and it felt like a waste of time",
        "The service was awful and the staff were rude",
        "This product broke after one day of use",
        "The experience was frustrating and full of delays",
        "I had a terrible time and will not return",
        "The update introduced bugs and made the app slower",
        "What a boring story, I almost fell asleep",
        "The design looks messy and outdated",
        "This was a weak performance with poor execution",
        "I am disappointed by the low quality",
        "Not good at all and not worth the money",
        "The food was cold and arrived very late",
        "I disliked the pacing, acting, and soundtrack",
        "Nothing worked correctly from start to finish",
        "The support team ignored my issue for days",
        "The camera quality is terrible in low light",
        "It feels cheap and performs badly",
        "This is one of the worst tools I have used",
        "The interface is confusing and annoying",
        "Bad visuals and no emotional impact",
        "The setup was difficult and full of errors",
        "The battery life is horrible for daily use",
        "A disappointing and forgettable experience",
        "The lessons were unclear and poorly organized",
        "I found the content useless and repetitive",
        "The feature set is weak and not very useful",
        "I would never watch this again",
        "The delivery was delayed and the item was damaged",
        "The team did a poor job on this release",
        "It looked promising but the result was terrible",
    ]

    neutral = [
        "The movie was okay and had both good and bad moments",
        "The service was average and nothing stood out",
        "This product is fine for basic everyday use",
        "The experience was acceptable but not memorable",
        "I had an ordinary time and nothing surprised me",
        "The update changed a few things but nothing major",
        "The story was simple and easy to follow",
        "The design is decent and fairly standard",
        "This was a moderate performance with mixed results",
        "The quality is reasonable for the price",
        "Not bad, not great, just acceptable",
        "The food was okay and arrived on schedule",
        "The pacing was uneven but still watchable",
        "Some parts worked well while others did not",
        "The support team eventually resolved the issue",
        "The camera quality is average indoors",
        "It feels standard and performs as expected",
        "This is a typical tool with basic features",
        "The interface is usable after a short adjustment",
        "The visuals were fine but not striking",
        "The setup took some time but was manageable",
        "The battery life is decent for casual use",
        "An average and predictable experience",
        "The lessons were straightforward but a bit dry",
        "I found the content okay overall",
        "The feature set covers the essentials",
        "I might watch this again if I have time",
        "The delivery was normal and the packaging was okay",
        "The team shipped a serviceable release",
        "It is neither impressive nor disappointing",
    ]
    rows = []
    for txt in positive:
        rows.append((txt, "positive"))
    for txt in negative:
        rows.append((txt, "negative"))
    for txt in neutral:
        rows.append((txt, "neutral"))
    return rows
